config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controller: {registrations: 'registrations'}
  resources :articles do
    resources :comments
  end
  resources :contacts
  root to:'pages#index'
  get 'pages/contact'
  get 'pages/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :message
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /articles or /articles.json
  def index
    @articles = Article.all.paginate(page: params[:page], per_page: 2)
    @lastthree= Article.last(3)
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = current_user.articles.build
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :authenticate_user!

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(params[:comment].permit(:body))
    @comment.user_id = current_user.id if current_user
    if @comment.save
      redirect_to article_path(@article), notice: "Your comment has been saved."
    else
      redirect_to 'new'
end
  end

  def update
    @article =Article.find(params[:article_id])
    @comment=@article.comments.find(params[:id])

    if @comment.update(params[:comment].permit(:body))
      redirect_to article_path(@article), notice:"Your comment has been updated."
    else
      render 'edit'
    end
  end

  def edit
    @article =Article.find(params[:article_id])
    @comment=@article.comments.find(params[:id])
  end

  def destroy
    @article =Article.find(params[:article_id])
    @comment=@article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), notice:"Your comment has been deleted."

  end


end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
      @contact = Contact.new
end
def create
      @contact = Contact.new(contact_params)
      if @contact.save
        redirect_to root_path
        name = params[:contact][:name]
        email = params[:contact][:email]
        message = params[:contact][:message]
        ContactMailer.contact_email(name, email, message).deliver
        flash[:success] = "Thanks for the message, we will be in touch soon."
      else
          redirect_to pages_contact_path
          flash[:danger] = "Opps, there was a problem! Please fill out all the fields."
      end
end


private
  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def index
    if current_user
    redirect_to articles_path
    end
      @articles= Article.last(3)

  end

  def contact
    @contact = Contact.new
  end

  def about
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private
  def sign_up_params
    params.require(:user).permit(
      :email,
      :password,
      :password_confirmation,
      :username,
      :firstname,
      :lastname
    )
  end

  def account_update_params
    params.require(:user).permit(
      :email,
      :password,
      :password_confirmation,
      :current_password,
      :username,
      :firstname,
      :lastname
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="row">
  <!-- Blog Post Content Column -->
  <div class="col-lg-8">
    <!-- Blog Post -->
    <!-- Title -->
    <h1 style="font-size: 62.5px;">
        <%= @article.title %>
    </h1>
    <!-- Author -->
    <p class="lead">
      <%= article.user.email %>
    </p>
    <hr>
    <!-- Date/Time -->
    <p><span class="glyphicon glyphicon-time"></span> Was Posted:
      <hr>
      <!-- Preview Image -->
      <hr>
      <!-- Post Content -->
        <%= @article.body %>
      <hr>
      <!-- Blog Comments -->



    <%= render @article.comments %>
      <!-- Comments Form -->
      <%= render 'comments/form' %>

      <div class="well">
        <h4></h4>
      </div>
      <hr>
      <!-- Posted Comments -->
      <!-- Comment -->
    </div>
    <!-- Blog Sidebar Widgets Column -->
  <div class="col-md-4">
    <!-- Blog Search Well -->
    <!-- Blog Categories Well -->
    <!-- Side Widget Well -->
    <div class="well">
      <h4>  </h4>
    </div>

  </div>
</div>
<%= link_to 'Edit', edit_article_path(@article)%>
<%= link_to "Back", articles_path %>

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<div class="row">
<!-- Blog article Content Column -->
<div class="col-lg-8">
<% @articles.each do |article| %>
<!-- Blog article -->
<!-- Title -->
<h4 style="font-size: 45.5px;"><%= link_to article.title, article %></h4>
<!-- Date/Time -->
<p><span class="glyphicon glyphicon-time"></span>
</p>
<!-- Author -->
<p>
Article created By:<strong> <%= article.user.email %></strong>
</p>
<hr>
<!-- articleed Comments -->
<!-- Comment -->
<% end %>
<%= link_to "New article", new_article_path, class: "btn btn-default btn-xs" %>
</div>
<!-- Blog Sidebar Widgets Column -->
<div class="col-md-4">
<div class="well">
<h4></h4>
<% @lastthree.each do |p| %>
Created by: <%= p.user.username %><br />
<strong><%= link_to p.title, p %></strong>
<p><%= truncate(p.body) %></p>
<% end %>
</div>
</div>
<%= will_paginate @articles%>
</div>
<br>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/comments/_comment.html.erb
<div class="media">
  <div class="pull-left">
    <%= comment.user.email %>
  </div>
    <div class="media-body">
      <p class="media-heading pull-right">
        <%= time_ago_in_words(comment.created_at) %>
      </p><br>
      <%= comment.body %>
    </div>
</div>
<%= link_to "Edit", edit_article_comment_path(comment.article, comment) %>
<%= button_to "Delete", [comment.article, comment], method: :delete, data: { confirm: "Are you sure?" } %>

app/views/comments/_form.html.erb
<%= simple_form_for ([@article, @article.comments.build]) do |f|%>

<%= f.input :body %>
<%= f.submit "Post your comment" %>
<% end%>

app/views/comments/edit.html.erb
<h1> Edit Comment</h1>
  <%= simple_form_for([@article, @comment]) do |f| %>
    <%= f.input :body %>
  <%= f.submit %>
<% end %>

app/views/layouts/_foot.html.erb
<footer class="footer-distributed navbar-black bg-black" style="position: fixed; bottom: 0px; width: 100%; height: 60px;">
<div class="footer-right">
<a href="#"><i class="fa fa-facebook"></i></a>
<a href="#"><i class="fa fa-twitter"></i></a>
<a href="#"><i class="fa fa-linkedin"></i></a>
<a href="#"><i class="fa fa-github"></i></a>
</div>
<div class="footer-left">
<p class="footer-links">
·
<%= link_to "Contact Us", pages_contact_path, class: "page-scroll" %>
.
<%= link_to "About Us", pages_about_path, class: "page-scroll" %>

·
</p>
<p> </p>
</div>
</footer>

app/views/layouts/_nav.html.erb
  <nav class="navbar navbar-expand-lg navbar-dark bg-black">
  <div class="container-fluid">
    <%= link_to "Article's", root_path, class:'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>

        </ul>



        <ul class="nav justify-content-end">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0>



        <li class="nav-item">
          <a class="nav-link" <%= link_to "Contact Us", pages_contact_path %></a>



        <li class="nav-item">
          <a class="nav-link" <%= link_to "About Us", pages_about_path %></a>
        </li>

        <li class="nav-item">
          <a class="nav-link" <%= link_to "View Articles", articles_path %></a>
        </li>



<% if !current_user%>
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Sign up", new_user_registration_path%></a>
        </li>

        <li class="nav-item">
          <a class="nav-link" <%= link_to "Sign in", new_user_session_path %></a>
        </li>
<% end %>




<% if current_user%>
    
            <li class="nav-item">
              <a class="nav-link" <%= link_to "Edit my profile", edit_user_registration_path%></a>


            <li class="nav-item">
              <a class="nav-link" <%= link_to "Sign out", destroy_user_session_path, method: :delete %></a>
            </li>


      </ul>
<% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link href="//stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <title>Article's</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'layouts/nav' %>



    <%= bootstrap_flash %>

      <div class='container'>
        <%= yield %>
      </div>
    <%= render 'layouts/foot' %>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/_mailer.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="well">
      <%= simple_form_for @contact do |f| %>
      <%= f.input :name %>
      <%= f.input :email %>
      <%= f.input :message %>
      <%= f.submit "Get in touch!", class: "btn btn-info" %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/about.html.erb
<!--About Page-->
<div class="row">
<div class="col-lg-12 text-center">
<h1>About Us</h1>
<p class="lead">Test Text</p>
<ul class="list-unstyled">
<li>List Item</li>
<li>List Item 2</li>
</ul>
</div>
</div>

app/views/pages/contact.html.erb
<!--Contact Page-->
<div class="row">
  <div class="col-lg-12 text-center">
    <h1>Contact Us</h1>
    <p class="lead">Test Text</p>
    <ul class="list-unstyled">
      <li> List Item </li>
      <li> List item 1 </li>
    </ul>

  </div>
<%= render 'pages/mailer' %>
</div>

app/views/pages/index.html.erb
<div class="row">
<div class="col-lg-8">
<!-- Blog Post -->
<!-- Title -->
<div class="jumbotron">
<h1>Welcome to Articles. </h1>
<p>Awesome applications built with Rails!</p>
<p></p>
</div>
</div>
<!-- Blog Sidebar Widgets Column -->
<div class="col-md-4">
<!-- Blog Categories Well -->
<!-- Side Widget Well -->
<div class="well">
<h4>Recent Posts</h4>
<% @articles.each do |a| %>
<strong> Created by:</strong> <%=a.user.email%> <br />
<strong> <%= link_to a.title, a %> </strong>
<p> <%=  truncate (a.body) %> </p>
<% end %>
</div>
</div>
</div>
<!-- /.row -->
<hr>